[workspace]

members = [
    "wa",
    "kyay",
]

exclude = [
    "dux" # for now it should be excluded because the different wgpu versions
          # in eframe and nannou conflict which web-sys version they want
]

resolver = "2"
