[package]
name = "dux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
nannou = "0.18.1"
unicode-normalization = "0.1.22"
wa = { path = "../wa" }